const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { buildInstructionExports, buildInstructionState, exportInstructions } = require('../src/export');
const { detectAllDrift } = require('../src/drift');
const { makeProjectTree } = require('./helpers');

function tree(configJson) {
    const base = {
        'CLAUDE.md': '# Hand written\n\n@AGENTS.md\n',
        'AGENTS.md': '# Hand written\n\n- a rule the project owns\n',
        '.harness': {
            'HARNESS.md': '# Shared\n\n- shared rule\n',
            llm: { 'claude.md': '# Claude\n\n- claude rule\n' },
            agents: { common: { 'reviewer.md': '# Reviewer\n' } }
        }
    };
    if (configJson !== undefined) {
        base['.harness']['config.json'] = configJson;
    }
    return base;
}

test('instructions are generated by default', () => {
    const root = makeProjectTree('soft-harness-instr-default-', tree());
    const exports = buildInstructionExports(root, { state: { assets: { instructions: [] } } });
    assert.ok(exports.length > 0, 'expected instruction exports without an opt-out');
});

// A project can own its instruction files (here, an .elpis/.personal convention)
// while still letting soft-harness manage skills, agents and settings.
test('instructions: external stops generation without touching the files', () => {
    const root = makeProjectTree('soft-harness-instr-external-', tree('{ "instructions": "external" }\n'));
    const before = fs.readFileSync(path.join(root, 'AGENTS.md'), 'utf8');

    assert.deepEqual(
        buildInstructionExports(root, { state: { assets: { instructions: [] } } }),
        [],
        'no instruction should be exported'
    );

    const result = exportInstructions(root, { state: { assets: { instructions: [] } } });
    assert.deepEqual(result.exported, [], 'nothing should be written');
    assert.equal(fs.readFileSync(path.join(root, 'AGENTS.md'), 'utf8'), before, 'AGENTS.md was modified');
});

test('instructions: external reports no instruction drift', () => {
    const root = makeProjectTree('soft-harness-instr-drift-', tree('{ "instructions": "external" }\n'));
    const drift = detectAllDrift(root, { state: { assets: { instructions: [] } } });
    assert.deepEqual(
        drift.filter((entry) => entry.type === 'instruction'),
        [],
        'hand-managed instruction files must not be reported as drift'
    );
});

// This is the failure that made the previous opt-out attempt evaporate: the
// state list was emptied, but the exporter re-adopted the targets on the next
// run because the fragments still existed.
test('instructions: external keeps the state list empty across runs', () => {
    const root = makeProjectTree('soft-harness-instr-state-', tree('{ "instructions": "external" }\n'));
    let state = { assets: { instructions: [{ llm: 'claude', target: 'CLAUDE.md', sources: [] }] } };
    state = { assets: { instructions: buildInstructionState(root, state) } };
    assert.deepEqual(state.assets.instructions, [], 'a stale state entry must not resurrect generation');
});

test('a malformed .harness/config.json fails loudly', () => {
    const root = makeProjectTree('soft-harness-instr-bad-', tree('{ not json\n'));
    assert.throws(
        () => buildInstructionExports(root, { state: { assets: { instructions: [] } } }),
        /config\.json/,
        'a broken config must not be silently ignored'
    );
});

test('an unrelated config key leaves instruction generation on', () => {
    const root = makeProjectTree('soft-harness-instr-other-', tree('{ "somethingElse": true }\n'));
    assert.ok(
        buildInstructionExports(root, { state: { assets: { instructions: [] } } }).length > 0,
        'only instructions: external should disable generation'
    );
});

// The dangerous case: state still lists targets from before the opt-out. The
// empty export list must not be read as "these are stale, delete them".
test('instructions: external never deletes a previously managed target', () => {
    const root = makeProjectTree('soft-harness-instr-prune-', tree('{ "instructions": "external" }\n'));
    const staleState = {
        assets: {
            instructions: [
                { llm: 'claude', target: 'CLAUDE.md', sources: ['.harness/HARNESS.md'] },
                { llm: 'codex', target: 'AGENTS.md', sources: ['.harness/HARNESS.md'] }
            ]
        }
    };

    exportInstructions(root, { state: staleState });

    assert.ok(fs.existsSync(path.join(root, 'AGENTS.md')), 'AGENTS.md was deleted');
    assert.ok(fs.existsSync(path.join(root, 'CLAUDE.md')), 'CLAUDE.md was deleted');
    assert.match(fs.readFileSync(path.join(root, 'AGENTS.md'), 'utf8'), /a rule the project owns/);
});

// A project can keep harness-managed instructions for some hosts and drop a
// host it does not use. Deleting the file is not enough: the exporter re-adopts
// the target whenever the shared fragments exist, so the exclusion has to be
// declared.
test('instructions.exclude drops one host and keeps the rest', () => {
    const root = makeProjectTree('soft-harness-instr-exclude-',
        tree('{ "instructions": { "exclude": ["gemini"] } }\n'));
    const llms = buildInstructionExports(root, { state: { assets: { instructions: [] } } })
        .map((entry) => entry.llm);

    assert.ok(!llms.includes('gemini'), 'gemini should be excluded');
    assert.ok(llms.includes('claude'), 'claude should still be generated');
    assert.ok(llms.includes('codex'), 'codex should still be generated');
});

test('instructions.exclude never deletes the excluded host file', () => {
    const root = makeProjectTree('soft-harness-instr-exclude-keep-',
        tree('{ "instructions": { "exclude": ["gemini"] } }\n'));
    fs.writeFileSync(path.join(root, 'GEMINI.md'), '# kept by hand\n', 'utf8');

    exportInstructions(root, {
        state: { assets: { instructions: [{ llm: 'gemini', target: 'GEMINI.md', sources: [] }] } }
    });

    assert.ok(fs.existsSync(path.join(root, 'GEMINI.md')), 'excluded host file was deleted');
});
