const path = require('path');
const { ensureDir, exists, readUtf8, toPosixRelative, writeUtf8 } = require('./fs-util');

function generateOutputs(rootDir, loadedRegistry) {
    const generated = [];
    const harnessRoot = path.join(rootDir, 'harness');
    const guidesRoot = loadedRegistry.registry.defaults && loadedRegistry.registry.defaults.guides_root
        ? path.resolve(harnessRoot, loadedRegistry.registry.defaults.guides_root)
        : path.join(harnessRoot, 'guides');

    for (const output of loadedRegistry.registry.outputs || []) {
        if (output.enabled === false) {
            continue;
        }

        const generatedPath = path.resolve(harnessRoot, output.generated_path);
        const content = buildOutputContent(output, loadedRegistry.registry.guides, guidesRoot, rootDir);
        ensureDir(path.dirname(generatedPath));
        writeUtf8(generatedPath, content);

        generated.push({
            id: output.id,
            target: output.target,
            scope: output.scope,
            generatedPath
        });
    }

    return generated;
}

function buildOutputContent(output, guideMap, guidesRoot, rootDir) {
    const lines = [];
    const guideBuckets = Array.isArray(output.guide_buckets) ? output.guide_buckets : [];

    lines.push('<!-- Generated by soft-harness. Do not edit directly. -->');
    lines.push(`# ${output.id}`);
    lines.push('');
    lines.push(`- target: ${output.target}`);
    lines.push(`- scope: ${output.scope}`);
    lines.push('');

    for (const bucket of guideBuckets) {
        const entries = Array.isArray(guideMap[bucket]) ? guideMap[bucket] : [];
        const matchingEntries = entries
            .map((entry) => normalizeGuideEntry(entry))
            .filter((entry) => entry.scope === output.scope);

        for (const entry of matchingEntries) {
            const fullPath = path.resolve(guidesRoot, bucket, entry.path);
            if (!exists(fullPath)) {
                continue;
            }

            lines.push('---');
            lines.push(`source: ${toPosixRelative(rootDir, fullPath)}`);
            lines.push('');
            lines.push(readUtf8(fullPath).trimEnd());
            lines.push('');
        }
    }

    return `${lines.join('\n')}\n`;
}

function normalizeGuideEntry(entry) {
    if (typeof entry === 'string') {
        return {
            path: entry,
            scope: 'project'
        };
    }

    return Object.assign({
        scope: 'project'
    }, entry);
}

module.exports = {
    generateOutputs
};
