const path = require('path');
const os = require('os');
const { ensureDir, exists, readUtf8, resolveTemplatePath, toPosixRelative, writeUtf8 } = require('./fs-util');

function generateOutputs(rootDir, loadedRegistry, options) {
    const generated = [];
    const harnessRoot = (options && options.harnessRoot) || path.join(rootDir, 'harness');
    const variables = createPathVariables(rootDir, harnessRoot);
    const guidesRoot = loadedRegistry.registry.defaults && loadedRegistry.registry.defaults.guides_root
        ? path.resolve(harnessRoot, loadedRegistry.registry.defaults.guides_root)
        : path.join(harnessRoot, 'guides');

    for (const output of loadedRegistry.registry.outputs || []) {
        if (output.enabled === false) {
            continue;
        }

        const generatedPath = resolveTemplatePath(output.generated_path, variables, harnessRoot);
        const content = buildOutputContent(output, loadedRegistry.registry, guidesRoot, rootDir);
        ensureDir(path.dirname(generatedPath));
        writeUtf8(generatedPath, content);

        generated.push({
            id: output.id,
            target: output.target,
            scope: output.scope,
            generatedPath
        });
    }

    return generated;
}

function buildOutputContent(output, registry, guidesRoot, rootDir) {
    if (output.content_type === 'mcp-json') {
        return buildMcpOutput(output, registry);
    }

    const guideMap = registry.guides;
    const lines = [];
    const guideBuckets = Array.isArray(output.guide_buckets) ? output.guide_buckets : [];

    lines.push('<!-- Generated by soft-harness. Do not edit directly. -->');
    lines.push(`# ${output.id}`);
    lines.push('');
    lines.push(`- target: ${output.target}`);
    lines.push(`- scope: ${output.scope}`);
    lines.push('');

    for (const bucket of guideBuckets) {
        const entries = Array.isArray(guideMap[bucket]) ? guideMap[bucket] : [];
        const matchingEntries = entries
            .map((entry) => normalizeGuideEntry(entry))
            .filter((entry) => entry.scope === output.scope);

        for (const entry of matchingEntries) {
            const fullPath = path.resolve(guidesRoot, bucket, entry.path);
            if (!exists(fullPath)) {
                continue;
            }

            lines.push('---');
            lines.push(`source: ${toPosixRelative(rootDir, fullPath)}`);
            lines.push('');
            lines.push(readUtf8(fullPath).trimEnd());
            lines.push('');
        }
    }

    return `${lines.join('\n')}\n`;
}

function buildMcpOutput(output, registry) {
    const capabilityIds = Array.isArray(output.capability_ids) ? new Set(output.capability_ids) : null;
    const servers = {};

    for (const capability of registry.capabilities || []) {
        if (capability.kind !== 'mcp') {
            continue;
        }

        if (capability.enabled === false) {
            continue;
        }

        if (capabilityIds && !capabilityIds.has(capability.id)) {
            continue;
        }

        if (capability.scope !== output.scope) {
            continue;
        }

        if (!(capability.target === output.target || capability.target === 'both' || output.target === 'both')) {
            continue;
        }

        const serverId = capability.server_id || capability.id;
        servers[serverId] = capability.server || {};
    }

    return `${JSON.stringify({ mcpServers: servers }, null, 2)}\n`;
}

function createPathVariables(rootDir, harnessRoot) {
    return {
        rootDir,
        harnessRoot,
        userHome: os.homedir()
    };
}

function normalizeGuideEntry(entry) {
    if (typeof entry === 'string') {
        return {
            path: entry,
            scope: 'project'
        };
    }

    return Object.assign({
        scope: 'project'
    }, entry);
}

module.exports = {
    generateOutputs
};
