const { normalizeContent } = require('./md-parse');

function buildImportStub(input) {
    const sources = normalizeImportSources(input);
    return [
        '<!-- Managed by soft-harness. Do not edit this file directly. -->',
        `<!-- Source: ${sources.join(' + ')} -->`,
        '<!-- Regenerate: soft-harness organize -->',
        '',
        ...sources.map((source) => `@${source}`),
        ''
    ].join('\n');
}

function buildConcatStub(input, commonContent, llmContent) {
    const blocks = normalizeConcatBlocks(input, commonContent, llmContent);
    return [
        '<!-- Managed by soft-harness. Do not edit this file directly. -->',
        `<!-- Source: ${blocks.map((block) => `.harness/${block.path}`).join(' + ')} -->`,
        '<!-- Regenerate: soft-harness organize -->',
        ...blocks.flatMap((block) => [
            `<!-- BEGIN ${block.path} -->`,
            '',
            normalizeContent(block.content || '').trim(),
            '',
            `<!-- END ${block.path} -->`
        ]),
        ''
    ].join('\n').replace(/\n{3,}/g, '\n\n');
}

function parseConcatStub(content) {
    const normalized = normalizeContent(content || '');
    const blocks = [];
    const outside = [];
    const lines = normalized.split('\n');
    let index = 0;

    while (index < lines.length) {
        const beginMatch = /^<!-- BEGIN ([^>]+) -->$/.exec(lines[index].trim());
        if (!beginMatch) {
            outside.push(lines[index]);
            index += 1;
            continue;
        }

        const blockLines = [];
        const blockPath = beginMatch[1];
        index += 1;
        while (index < lines.length && lines[index].trim() !== `<!-- END ${blockPath} -->`) {
            blockLines.push(lines[index]);
            index += 1;
        }
        blocks.push({
            path: blockPath,
            content: blockLines.join('\n').trim()
        });
        if (index < lines.length) {
            index += 1;
        }
    }

    const outsideContent = outside.join('\n')
        .replace(/^<!-- Managed by soft-harness.*$/m, '')
        .replace(/^<!-- Source:.*$/m, '')
        .replace(/^<!-- Regenerate:.*$/m, '')
        .trim();

    return {
        blocks,
        outside: outsideContent
    };
}

function extractImportStubDelta(content) {
    const normalized = normalizeContent(content || '');
    const lines = normalized.split('\n');
    const extra = [];

    for (const line of lines) {
        if (line.startsWith('<!-- Managed by soft-harness')) {
            continue;
        }
        if (line.startsWith('<!-- Source:')) {
            continue;
        }
        if (line.startsWith('<!-- Regenerate:')) {
            continue;
        }
        if (line.startsWith('@.harness/')) {
            continue;
        }
        extra.push(line);
    }

    return extra.join('\n').trim();
}

function normalizeImportSources(input) {
    if (Array.isArray(input) && input.length > 0) {
        return input;
    }

    const llm = String(input || '').trim() || 'claude';
    return [
        '.harness/HARNESS.md',
        '.harness/memory/shared.md',
        `.harness/llm/${llm}.md`,
        `.harness/memory/llm/${llm}.md`
    ];
}

function normalizeConcatBlocks(input, commonContent, llmContent) {
    if (Array.isArray(input) && input.length > 0) {
        return input;
    }

    const llm = String(input || '').trim() || 'claude';
    return [
        { path: 'HARNESS.md', content: commonContent || '' },
        { path: 'memory/shared.md', content: '' },
        { path: `llm/${llm}.md`, content: llmContent || '' },
        { path: `memory/llm/${llm}.md`, content: '' }
    ];
}

module.exports = {
    buildConcatStub,
    buildImportStub,
    extractImportStubDelta,
    parseConcatStub
};
