const path = require('node:path');
const { normalizeContent } = require('./md-parse');

const IMPORT_LINE_PATTERN = /^@(?:\.\.\/)*\.harness\//;

const SOFT_HARNESS_PROMPT_START = '<!-- soft-harness prompt:start -->';
const SOFT_HARNESS_PROMPT_END = '<!-- soft-harness prompt:end -->';
const SOFT_HARNESS_PROMPT_LINES = [
    SOFT_HARNESS_PROMPT_START,
    '## Soft Harness',
    '',
    'Soft Harness provides two skills:',
    '',
    '- `analyze`: inspect Claude Code, Codex, and other host state without changing host files.',
    '- `organize`: update host instruction/config files and refresh `.harness` after the user chooses a shared or LLM-specific change.',
    '',
    'Use `organize` whenever you modify `AGENTS.md` or `CLAUDE.md`; first ask the user whether the change should be shared ' +
        'with other LLM instruction files or kept LLM-specific. Only sync to other LLM files when the user chooses a shared change.',
    SOFT_HARNESS_PROMPT_END
];

function buildImportStub(input, instructionPath) {
    const sources = normalizeImportSources(input);
    const prefix = importPrefixFor(instructionPath);
    return [
        '<!-- Managed by soft-harness. Do not edit this file directly. -->',
        `<!-- Source: ${sources.join(' + ')} -->`,
        '<!-- Regenerate: soft-harness organize -->',
        '',
        ...SOFT_HARNESS_PROMPT_LINES,
        '',
        ...sources.map((source) => `@${prefix}${source}`),
        ''
    ].join('\n');
}

// Sources are recorded relative to the harness root, but a host resolves a
// relative import against the directory of the file containing it. An
// instruction file nested below that root (`.claude/CLAUDE.md`) must climb back
// out, or every import points at a `.harness` directory that does not exist.
function importPrefixFor(instructionPath) {
    const normalized = String(instructionPath || '.').split(path.sep).join('/');
    const dir = path.posix.dirname(normalized);
    if (!dir || dir === '.' || dir === '/') {
        return '';
    }
    const depth = dir.split('/').filter((part) => part && part !== '.').length;
    return '../'.repeat(depth);
}

function isImportStubLine(line) {
    return IMPORT_LINE_PATTERN.test(String(line || '').trim());
}

function hasImportStubSources(content) {
    return normalizeContent(content || '')
        .split('\n')
        .some((line) => isImportStubLine(line));
}

function buildConcatStub(input, commonContent, llmContent) {
    const blocks = normalizeConcatBlocks(input, commonContent, llmContent);
    return [
        '<!-- Managed by soft-harness. Do not edit this file directly. -->',
        `<!-- Source: ${blocks.map((block) => `.harness/${block.path}`).join(' + ')} -->`,
        '<!-- Regenerate: soft-harness organize -->',
        '',
        ...SOFT_HARNESS_PROMPT_LINES,
        '',
        ...blocks.flatMap((block) => [
            `<!-- BEGIN ${block.path} -->`,
            '',
            normalizeContent(block.content || '').trim(),
            '',
            `<!-- END ${block.path} -->`
        ]),
        ''
    ].join('\n').replace(/\n{3,}/g, '\n\n');
}

function parseConcatStub(content) {
    const normalized = normalizeContent(content || '');
    const blocks = [];
    const outside = [];
    const lines = normalized.split('\n');
    let index = 0;

    while (index < lines.length) {
        const beginMatch = /^<!-- BEGIN ([^>]+) -->$/.exec(lines[index].trim());
        if (!beginMatch) {
            outside.push(lines[index]);
            index += 1;
            continue;
        }

        const blockLines = [];
        const blockPath = beginMatch[1];
        index += 1;
        while (index < lines.length && lines[index].trim() !== `<!-- END ${blockPath} -->`) {
            blockLines.push(lines[index]);
            index += 1;
        }
        blocks.push({
            path: blockPath,
            content: blockLines.join('\n').trim()
        });
        if (index < lines.length) {
            index += 1;
        }
    }

    const outsideContent = outside.join('\n')
        .replace(createSoftHarnessPromptPattern(), '')
        .replace(/^<!-- Managed by soft-harness.*$/m, '')
        .replace(/^<!-- Source:.*$/m, '')
        .replace(/^<!-- Regenerate:.*$/m, '')
        .trim();

    return {
        blocks,
        outside: outsideContent
    };
}

function extractImportStubDelta(content) {
    const normalized = normalizeContent(content || '').replace(createSoftHarnessPromptPattern(), '');
    const lines = normalized.split('\n');
    const extra = [];

    for (const line of lines) {
        if (line.startsWith('<!-- Managed by soft-harness')) {
            continue;
        }
        if (line.startsWith('<!-- Source:')) {
            continue;
        }
        if (line.startsWith('<!-- Regenerate:')) {
            continue;
        }
        if (isImportStubLine(line)) {
            continue;
        }
        extra.push(line);
    }

    return extra.join('\n').trim();
}

function createSoftHarnessPromptPattern() {
    return new RegExp(`${escapeRegExp(SOFT_HARNESS_PROMPT_START)}[\\s\\S]*?${escapeRegExp(SOFT_HARNESS_PROMPT_END)}`, 'g');
}

function escapeRegExp(value) {
    return String(value).replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

function normalizeImportSources(input) {
    if (Array.isArray(input) && input.length > 0) {
        return input;
    }

    const llm = String(input || '').trim() || 'claude';
    return [
        '.harness/HARNESS.md',
        '.harness/memory/shared.md',
        `.harness/llm/${llm}.md`,
        `.harness/memory/llm/${llm}.md`
    ];
}

function normalizeConcatBlocks(input, commonContent, llmContent) {
    if (Array.isArray(input) && input.length > 0) {
        return input;
    }

    const llm = String(input || '').trim() || 'claude';
    return [
        { path: 'HARNESS.md', content: commonContent || '' },
        { path: 'memory/shared.md', content: '' },
        { path: `llm/${llm}.md`, content: llmContent || '' },
        { path: `memory/llm/${llm}.md`, content: '' }
    ];
}

module.exports = {
    buildConcatStub,
    buildImportStub,
    extractImportStubDelta,
    hasImportStubSources,
    importPrefixFor,
    isImportStubLine,
    parseConcatStub
};
